Ticket 176592872
admetricks/slay pull request #16
Opened 2021-01-28 19:01 UTC by arlopezg

2021-01-29 19:04 UTC, pdelsol commented
![image](https://user-images.githubusercontent.com/2031318/106316479-91049d00-624b-11eb-891a-880fbe8c7dc8.png)


Creo que la instruccion de obetner token deberia ir a la izquierda tambien en el parrafo principal, porque de primera vista no lo vi ahi en la parte del codigo,

2021-01-29 19:11 UTC, pdelsol commented
![image](https://user-images.githubusercontent.com/2031318/106317169-ac23dc80-624c-11eb-92a7-fc79682f6a27.png)

Escritorio no "De escritorio"

2021-01-29 19:12 UTC, pdelsol commented
![image](https://user-images.githubusercontent.com/2031318/106317211-bc3bbc00-624c-11eb-8ce8-d17e5b230df1.png)

en los filtro comunes, 

deberia decir el nombre del parametro  en la explicación..



Dispositivos:

Restringe tus consultas según el tipo de dispositivo que más te interese.

El campo se llama `devices` y sus IDs son:

2021-01-29 19:13 UTC, pdelsol requested changes
minors detallados en los comentarios

2021-01-29 19:27 UTC, arlopezg commented
> 
> en los filtro comunes,
> 
> deberia decir el nombre del parametro en la explicación..
> 
> ## asi:
> Dispositivos:
> 
> Restringe tus consultas según el tipo de dispositivo que más te interese.
> 
> El campo se llama `devices` y sus IDs son:

Que tal asi?

![image](https://user-images.githubusercontent.com/8508658/106318553-dbd3e400-624e-11eb-9086-bf1b9c0116be.png)

2021-01-30 00:13 UTC, pdelsol commented
@arlopezg fino perro

2021-01-30 00:13 UTC, pdelsol approved these changes

2021-02-01 13:03 UTC, merged