docs(market-report): Include optionally industries
admetricks/slay pull request #33
Opened 2021-11-16 19:17 UTC by vitorohe

# Story

Based on these changes https://github.com/admetricks/clientela/pull/385

2021-11-17 12:49 UTC, pdelsol requested changes
Creo que faltaría en el ejemplo ponerle como se pasan las industrias,
ademas de poner que es opcional

2021-11-17 13:26 UTC, vitorohe commented
> Creo que faltaría en el ejemplo ponerle como se pasan las industrias, ademas de poner que es opcional

¿Eso se hace desde Clientela o Slay o ambos?

2021-11-19 13:43 UTC, pdelsol commented
> > Creo que faltaría en el ejemplo ponerle como se pasan las industrias, ademas de poner que es opcional
> 
> ¿Eso se hace desde Clientela o Slay o ambos?

no estoy seguro :(

2021-11-19 22:07 UTC, vitorohe commented on source/includes/api.html.md.erb
> +        <span class="param__required" title="Requerido">*</span>
missing `required` symbol, this code made the change (already updated in wiki)

before
```
    return markRequiredParams(result);
```

after
```
    if (requiredParams.length) {
        return markRequiredParams(result);
    } else {
        return result;
    }
```

2021-11-19 22:07 UTC, vitorohe commented on source/includes/snippets/_post-datos-de-mercado.md
> +$endpoint = 'https://clientela.admetricks.com/market-report/data/v3/?day=2020-10-01&country=1&device=1&ad_type=1'
fix, it was asking for industry report

2021-11-19 22:07 UTC, vitorohe commented on source/includes/snippets/_post-datos-de-mercado.md
> +> Ejemplo de petición filtrando por industrias
add samples to filter by industries

2021-11-19 22:07 UTC, vitorohe commented on source/includes/snippets/_post-obtener-alcance-incremental.md
> +response = requests.post('https://clientela.admetricks.com/reach/incremental/', headers=headers, data=data)
fix sample

2021-11-19 22:08 UTC, vitorohe commented
Now it's more complete @pdelsol @Jkaiser001

2021-11-22 12:42 UTC, Jkaiser001 approved these changes
LGTM

2021-11-22 12:51 UTC, pdelsol approved these changes
ahi si

2021-11-22 12:53 UTC, merged